update

diff --git a/preppics b/preppics
--- a/preppics
+++ b/preppics
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: preppics,v 1.2 2020/11/23 19:00:47 fulford Exp fulford $
+# $Id: preppics,v 1.3 2021/01/30 12:49:52 fulford Exp $
 # $Source: /src/admin/usr/local/etc/RCS/preppics,v $
-# $Revision: 1.2 $
+# $Revision: 1.3 $
 # Author C W Fulford.
 # Copyright 2019 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: preppics,v 1.2 2020/11/23 19:00:47 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: preppics,v 1.3 2021/01/30 12:49:52 fulford Exp $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
 while [ $# -gt 0 ] ;do
 	case $1 in 
@@ -16,11 +16,11 @@ while [ $# -gt 0 ] ;do
 		-d) set -x;debug=0;shift;;
 		-h) hostid=$2;shift 2;;			
 		-v) verbose=:;shift;;
-		-V) echo "$cmd $Revision: 1.2 $ $Date: 2020/11/23 19:00:47 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.3 $ $Date: 2021/01/30 12:49:52 $"|awk '{print $1,$3,$6}';exit;;  
 		*) files="$files $1";shift;;
 	esac
 done
-
+[ -x exiftool ] || echo "$cmd: exiftool not found";exit 1
 config=${config:-/usr/local/etc/${cmd}.cf
 [ -r $config ]||{echo "$cmd: Can't find $config";exit 1}
 #eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`
